# Generated by Django 5.1.3 on 2025-11-27 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], max_length=5)),
                ('duration', models.IntegerField(help_text='Duration in minutes')),
                ('position', models.IntegerField(help_text='Order/position in route')),
                ('from_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departing_routes', to='routes.airport')),
                ('to_airport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arriving_routes', to='routes.airport')),
            ],
            options={
                'unique_together': {('from_airport', 'direction')},
            },
        ),
    ]
