# Generated by Django 5.1.3 on 2025-11-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set(),
        ),
    ]
